# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/convolutionSystem/convolutionSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem || ORIG_REF_NAME==convolutionSystem} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_processing_system7_0_0/convolutionSystem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_processing_system7_0_0 || ORIG_REF_NAME==convolutionSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_axi_dma_0_0/convolutionSystem_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_axi_dma_0_0 || ORIG_REF_NAME==convolutionSystem_axi_dma_0_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/convolutionSystem_topConv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_topConv_0_0 || ORIG_REF_NAME==convolutionSystem_topConv_0_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_auto_pc_0/convolutionSystem_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_auto_pc_0 || ORIG_REF_NAME==convolutionSystem_auto_pc_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_ps7_0_axi_periph_0/convolutionSystem_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==convolutionSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_rst_ps7_0_100M_0/convolutionSystem_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==convolutionSystem_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_axis_dwidth_converter_0_0/convolutionSystem_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_axis_dwidth_converter_0_0 || ORIG_REF_NAME==convolutionSystem_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_xbar_0/convolutionSystem_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_xbar_0 || ORIG_REF_NAME==convolutionSystem_xbar_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_auto_us_0/convolutionSystem_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_auto_us_0 || ORIG_REF_NAME==convolutionSystem_auto_us_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_auto_us_1 || ORIG_REF_NAME==convolutionSystem_auto_us_1} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_auto_pc_1/convolutionSystem_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_auto_pc_1 || ORIG_REF_NAME==convolutionSystem_auto_pc_1} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_axi_mem_intercon_0/convolutionSystem_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_axi_mem_intercon_0 || ORIG_REF_NAME==convolutionSystem_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_xlconcat_0_0/convolutionSystem_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_xlconcat_0_0 || ORIG_REF_NAME==convolutionSystem_xlconcat_0_0} -quiet] -quiet

# IP: bd/convolutionSystem/ip/convolutionSystem_system_ila_0_0/convolutionSystem_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convolutionSystem_system_ila_0_0 || ORIG_REF_NAME==convolutionSystem_system_ila_0_0} -quiet] -quiet

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/convolutionSystem_ooc.xdc
