# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.srcs/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/convolutionSystem_topConv_0_0.xci
# IP: The module: 'convolutionSystem_topConv_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/src/convBuffer64/convBuffer64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convBuffer64 || ORIG_REF_NAME==convBuffer64} -quiet] -quiet

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/src/testing.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_topConv_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.srcs/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/convolutionSystem_topConv_0_0.xci
# IP: The module: 'convolutionSystem_topConv_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/src/convBuffer64/convBuffer64.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==convBuffer64 || ORIG_REF_NAME==convBuffer64} -quiet] -quiet

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_topConv_0_0/src/testing.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_topConv_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
