# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.srcs/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1.xci
# IP: The module: 'convolutionSystem_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.srcs/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1.xci
# IP: The module: 'convolutionSystem_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/niranjan/XilinxToolsProjects/convolutionSystem/convolutionSystem.gen/sources_1/bd/convolutionSystem/ip/convolutionSystem_auto_us_1/convolutionSystem_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'convolutionSystem_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
